name: Startup Venture Network
favicon: null
layout_spectrum: 0.50662
typography_spectrum: 0.7011073317844421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfb'
    - '#86aabc'
    - '#151412'
    - '#60534d'
    - '#c67d47'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6913981894031167
  rhythmicContrast: 0.8083075459580868
purpose: []
