typography_spectrum: 0.7011073317844421
color:
  brandColors:
    - '#fdfdfb'
    - '#86aabc'
    - '#151412'
    - '#60534d'
    - '#c67d47'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.6913981894031167
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50662
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6fcd129-c5b0-4fa9-bc4f-1dff2d698ca3.png
name: Startup Venture Network
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Accelerating Your Funding Success
purpose: []
